language: android
before_install:
 - chmod +x gradlew
android:
    licenses:
      - 'android-sdk-preview-license-.+'
      - 'android-sdk-license-.+'
      - 'google-gdk-license-.+'
  components:
    - build-tools-25.17
    - android-25